### ISSUE TITLE
Sequence length limitation?

### ISSUE THREAD

**Issue by ktsirigos** [phngs/allestm#2]
Hi,

I got this error when trying to run allesTM on some of my sequences (some have run successfully already):

The sequence cannot be longer than 1046 amino acids.

Does this mean that allesTM cannot handle longer sequences?

**Comment by phngs** [comment]
Hi. That is true, the LSTM is trained on a maximum sequence length of 1046,
therefore it is not possible to use longer sequences. It should be fine,
however, to split your sequence and so separate predictions.

**Comment by ktsirigos** [comment]
Ah, so you mean, if I have e.g. 3000 AA, predict the sequence in 3 steps, e.g. 0-1000, 1001-2000 and 2001-3000?

**Comment by phngs** [comment]
Yes, that should work. If you only want to predict for a few proteins, you
could also predict
0-1000
500-1500
1000-2000
1500-2500
2000-3000
and check if the overlapping regions agree on the results, just to make
sure that the predictions are valid.

**Comment by ktsirigos** [comment]
great thank you! Will try as you suggest :)
